#!/bin/bash

#************************************************************#
#                       Corticotropic                        #
#                            by                              #
#                  Debanjum Singh Solanky                    #
#                      April 24, 2014                        #
#                                                            #
#             Application Installation Script                #
#            Stream Media from the Web on VLC                #
#                         ./Install                          #
#************************************************************#

echo "Creating Local Application Directory"
mkdir -p ~/.corticotropic
echo "Copying Application Files"
cp Play ~/.corticotropic/
cp CreateLibrary ~/.corticotropic/
cp .corticotropic.png ~/.corticotropic/
echo "Installing Application"
mkdir -p ~/.local/share/mime/packages
cp ./Assets/application-x-corticotropic.xml ~/.local/share/mime/packages/
cp ./Assets/corticotropic.desktop ~/.local/share/applications/
sudo chmod +x ~/.corticotropic/Play ~/.corticotropic/CreateLibrary
sudo ln -sf ~/.corticotropic/Play /usr/bin/corticotropic
echo "Updating Application Database"
update-desktop-database ~/.local/share/applications
update-mime-database    ~/.local/share/mime
#sudo echo "application/x-corticotropic=corticotropic.desktop" >> usr/share/applications/defaults.list
