#!/bin/bash
#************************************************************#
#                      Corticotropic                         #
#                            by                              #
#                  Debanjum Singh Solanky                    #
#                      April 24, 2014                        #
#                                                            #
#              Stream Media from the Web on VLC              #
#                ./Play [Filename/SearchTerm]                #
#************************************************************#

[ $# -eq 0 ] && ( 

# RETRIEVING MEDIA FILENAME FROM FILEPATH [Delete Root Path, Punctutations, Digits and Extension]
media=`echo "$0" | sed -n 's/^.*music\/\(.*\).ctp$/\1/p' | tr [:digit:] ' ' | tr [:punct:] ' ' | tr -s [:blank:]`

# EXTRACTING TOP MEDIA URL FROM DUCKDUCKGO
mediaurl=`curl -s http://api.duckduckgo.com/?q="! site:youtube.com $media"\&format=json\&pretty=1\&no_redirect=1 | sed -n 's/^.*\"Redirect" \: \"\(.*\)\"\,.*$/\1/p'`

# ERROR CATCHING
[[ "$mediaurl" = "" ]] && ( notify-send "Unable to Retrieve Media" "Please Check Your Internet Connection" -t 500; )

# DEBUGGER
notify-send "$media $mediaurl" -t 500;

# PLAYING URL OVER VLC
`vlc --playlist-enqueue --play-and-exit --started-from-file $mediaurl &> ~/.corticotropic/.ctp.log`  #For Top Quality Video
#`vlc --playlist-enqueue --play-and-exit --started-from-file $mediaurl&fmt=18 &> ~/.corticotropic/.ctp.log`  #For Lowest Quality Video
) || ( 

[ $# -eq 1 ] && ( 

# RETRIEVING MEDIA FILENAME FROM FILEPATH [Delete Root Path, Punctutations, Digits and Extension]
media=`echo "$1" | sed -n 's/^.*music\/\(.*\).ctp$/\1/p' | tr [:digit:] ' ' | tr [:punct:] ' ' | tr -s [:blank:]`

# EXTRACTING TOP MEDIA URL FROM DUCKDUCKGO
mediaurl=`curl -s http://api.duckduckgo.com/?q="! site:youtube.com $media"\&format=json\&pretty=1\&no_redirect=1 | sed -n 's/^.*\"Redirect" \: \"\(.*\)\"\,.*$/\1/p'`

# ERROR CATCHING
[[ "$mediaurl" = "" ]] && ( notify-send "Unable to Retrieve Media" "Please Check Your Internet Connection" -t 500; )

# DEBUGGER
notify-send "$media $mediaurl" -t 500;

# PLAYING URL OVER VLC
`vlc --playlist-enqueue --play-and-exit --started-from-file $mediaurl &> ~/.corticotropic/.ctp.log`  #For Top Quality Video
#`vlc --playlist-enqueue --play-and-exit --started-from-file $mediaurl&fmt=18 &> ~/.corticotropic/.ctp.log`  #For Lowest Quality Video
))
